server:
  port: 5071

spring:
  profiles:
    active: list1
  # ==============================================================
  # = Proprietà Fonte Dati PostgreSQL
  # ==============================================================
  datasource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://localhost:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
# ==============================================================
# = Proprietà Servizio gestUser
# ==============================================================           
gestuser:
  userId: Cristian
  password: 123Stella
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  
# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 86400
    secret: 123_Stella
