server:
  port: 5071

spring:
  application:
    name: PriceArtWebService
  cloud:
    config:
      # indirizzo riferimento config server
      uri: http://localhost:8888
      # profilo attivo
      profile: list100
      # branch git da usare da cui caricare la configurazione del config server
      label: list3
  # ==============================================================
  # = Proprietà Fonte Dati PostgreSQL
  # ==============================================================
  datasource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://localhost:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: health,info,metrics
        
# ==============================================================
# = Actuator Info
# ==============================================================
info:
  assistenza:
    nome: "Cristian Bulgarelli"
  nome:
    nome-app: "PriceArt Web Service - Versione Autenticazione JWT"
# ==============================================================
# = Proprietà Servizio gestUser
# ==============================================================           
gestuser:
  userId: Cristian
  password: 123Stella
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  
# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 86400
    secret: 123_Stella
