# ==============================================================
# = SPRING API GATEWAY
# ==============================================================
server:
  port: 8765
  tomcat:
    threads:
      max: 5
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: SpringApiGateway
  lifecycle:
    timeout-per-shutdown-phase: 15s
  
  cloud:
    gateway:
      httpclient:
        #Timeout di connessione in ms
        connect-timeout: 2000 #2s
        #Timeout di risposta in s
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      default-filters:
        - name: RequestRateLimiter
          args:
            # filtro redis serve per limitare il numero di chiamate accettate per utente al secondo (per evitare attacchi DDoS)
            #Numero di token inseriti nel bucket al secondo (se in 1 secondo vengono inseriti più di 10 token nel bucket di redis, quindi abbiamo più di 10 chiamate al secondo, allora redis interverrà...)
            # It's how many requests per second do you want a user to be allowed to do, without any dropped requests.
            # This is the rate that the token bucket is filled.
            redis-rate-limiter.replenishRate: 10
            #Picco di token per utente inseriti nel bucket in un secondo
            # Es.: se un utente raggiunge al secondo 0 le 20 richieste massime consentite, ed ogni secondo ne recupera 10, dovrà attendere fino al secondo 3 per poter fare nuove chiamate....
            # It's the maximum number of requests a user is allowed to do in a single second.
            # This is the number of tokens the token bucket can hold.
            # Setting this value to zero will block all requests.
            redis-rate-limiter.burstCapacity: 10
            #Numero di token per ciascuna chiamata (ogni chiamata inserisce 1 token nel bucket del redis)
            redis-rate-limiter.requestedTokens: 1
            #key-resolver: '#{@userKeyResolver}'
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      enabled: true

      # ==============================================================
      # = Route Parameters
      # ==============================================================
      routes:
        - id: articoliModule
          uri: lb://ProductsWebService
          predicates:
            - Path=/api/articoli/**
          filters:
            - name: CircuitBreaker
              args:
                name: articoliCircuitBreaker
                fallbackUri: forward:/articolo-fallback
        - id: prezziModule
          uri: lb://PriceArtWebService
          predicates:
            - Path=/api/prezzi/**
          filters:
            - name: CircuitBreaker
              args:
                name: prezziCircuitBreaker
                fallbackUri: forward:/prezzo-fallback
        - id: listinoModule
          uri: lb://PriceArtWebService
          predicates:
            - Path=/api/listino/**
        - id: authModule
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

  # ==============================================================
  # = Redis Parameters
  # ==============================================================
  redis:
    connect-timeout: 2s
    host: localhost
    port: 6379
    timeout: 1s

# ==============================================================
# = Resilience4j Parameters
# ==============================================================
resilience4j:
  circuitbreaker:
    configs:
      default:
        #soglia in percentuali di fallimenti che che determina l'apeWrtura del circuito
        failureRateThreshold: 50
        #numero di chiamate di riferimento
        slidingWindowSize: 5
        #tempo di durata dello stato di circuito aperto
        wait-duration-in-open-state: 20000
        #numero di chiamate in stato half open
        permittedNumberOfCallsInHalfOpenState: 5
        #Se impiega più di un secondo viene conteggiato come lento
        slow-call-duration-threshold: 1000
        slow-call-rate-threshold: 50.00

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s

# ==============================================================
# = Eureka Properties  
# = Nota: prima di attivare il servizio servono tre heartbeat
# ==============================================================
eureka:
  # ==============================================================
  # = Impostazioni Instance
  # ==============================================================
  instance:
    #intervallo di attesa prima della rimozione del servizio (def 90 sec)
    lease-expiration-duration-in-seconds: 60
    #intervallo di invio dell'heartbeat (def 30 sec)
    leaseRenewalIntervalInSeconds: 15
    #id di identificazione dell'istanza
    instanceId: ${server.port}-${spring.application.name}
    #registrazione per indirizzo ip (defualt hostname)
    preferIpAddress: true
  # ==============================================================
  # = Impostazioni Client
  # ==============================================================
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:BimBumBam_2018@localhost:8761/eureka/}
    #time out di connessione in secondi al server Eureka (def 5 sec) 
    eureka-server-connect-timeout-seconds: 8


#==============================================================
# = Logs Parameters
# ==============================================================        
logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud: DEBUG
    io:
      github:
        resilience4j: DEBUG
    #org.springframework.security: DEBUG 

# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
  header: Authorization
  secret: $123_Stella@xantrix.it

management:
  endpoints:
    web:
      exposure:
        include: '*'