# ==============================================================
# = Config Server Base
# ==============================================================
server:
  port: 8888

# ==============================================================
# = Profilo Attivo
# ==============================================================
spring:
  config:
    use-legacy-processing: false
  profiles:
    active: github

# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: health,info,metrics

#endpoint: http://localhost:8888/{application-name}/{profile}[/{label}]

# ==============================================================
# = Logs Parameters
# ==============================================================
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.security: DEBUG

# ==============================================================
# = Security Parameters
# ==============================================================
sicurezza:
  userpwd: 'BimBumBam_2018'     # password utente che accede a tutti gli endpoint del config server, actuator escluso
  adminpwd: 'MagicaBula_2018'   # password admin che accede a tutti gli endpoint del config server, actuator incluso