# ==============================================================
# = Authentication Server JWT
# = Profilo GIT
# ==============================================================
spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: file:///home/cristian/git_repo/udemy/udemy-spring-boot-and-spring-cloud-git-config-repository
  config:
    activate:
      on-profile: git

# ==============================================================
# = Actuator Info
# ==============================================================
info:
  assistenza:
    nome: "Cristian Bulgarelli"
  nome:
    nome-app: "Config-Server"
    profilo: "GIT"
